sudo: required
services:
  - docker

before_install: 
  - docker build -t kujjuarun/docker-react -f Dockerfile.dev .


script: 
  - docker run -e CI=true kujjuarun/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-891377184987"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

  



